"""Controller-side analysis utilities for AOMQTT evaluation results.

This module aggregates controller feedback generated by the v0.9.x
control-plane experiments.  It intentionally depends only on the Python
standard library so that the evaluation workflow can run in a minimal
research environment.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping, Sequence


SCHEMA_VERSION = 1

ACK_STATUS_ALIASES = {
    "accept": "accepted",
    "accepted": "accepted",
    "ok": "accepted",
    "success": "accepted",
    "reject": "rejected",
    "rejected": "rejected",
    "invalid": "rejected",
    "expired": "expired",
    "timeout": "timeout",
    "timed_out": "timeout",
    "missing_ack": "timeout",
}

APPLICATION_STATUS_ALIASES = {
    "apply": "applied",
    "applied": "applied",
    "ok": "applied",
    "success": "applied",
    "fail": "failed",
    "failed": "failed",
    "error": "failed",
    "timeout": "timeout",
    "timed_out": "timeout",
}

ACK_FILE_HINTS = (
    "ack",
    "controller_ack",
    "policy_ack",
)

STATUS_FILE_HINTS = (
    "status",
    "controller_status",
    "policy_status",
    "deployment_status",
)

JSONL_FILE_HINTS = (
    "controller_feedback",
    "controller_events",
    "deployment_events",
)


@dataclass(frozen=True)
class ControllerEvent:
    """Normalized controller-side feedback event."""

    run_id: str
    scenario: str
    kind: str
    timestamp: str = ""
    client_id: str = "unknown"
    policy_id: str = "unknown"
    sequence_no: str = ""
    status: str = "unknown"
    reason_code: str = "unknown"
    source_file: str = ""

    def as_row(self) -> dict[str, str]:
        return {
            "schema_version": str(SCHEMA_VERSION),
            "run_id": self.run_id,
            "scenario": self.scenario,
            "kind": self.kind,
            "timestamp": self.timestamp,
            "client_id": self.client_id,
            "policy_id": self.policy_id,
            "sequence_no": self.sequence_no,
            "status": self.status,
            "reason_code": self.reason_code,
            "source_file": self.source_file,
        }


def _first_nonempty(row: Mapping[str, object], keys: Sequence[str], default: str = "") -> str:
    for key in keys:
        value = row.get(key)
        if value is None:
            continue
        text = str(value).strip()
        if text:
            return text
    return default


def _normalize_status(value: str, *, kind: str) -> str:
    value = (value or "").strip().lower()
    if not value:
        return "unknown"
    if kind == "ack":
        return ACK_STATUS_ALIASES.get(value, value)
    if kind == "status":
        return APPLICATION_STATUS_ALIASES.get(value, value)
    return value


def _infer_run_and_scenario(path: Path, results_root: Path) -> tuple[str, str]:
    try:
        rel = path.relative_to(results_root)
    except ValueError:
        rel = path
    parts = rel.parts
    run_id = parts[0] if len(parts) >= 2 else "unknown-run"
    scenario = parts[1] if len(parts) >= 3 else "unknown-scenario"
    return run_id, scenario


def _infer_kind_from_path(path: Path) -> str | None:
    name = path.name.lower()
    stem = path.stem.lower()
    if path.suffix.lower() == ".jsonl" and any(hint in stem for hint in JSONL_FILE_HINTS):
        return None
    if any(hint in stem for hint in ACK_FILE_HINTS):
        return "ack"
    if any(hint in stem for hint in STATUS_FILE_HINTS):
        return "status"
    if "ack" in name:
        return "ack"
    if "status" in name:
        return "status"
    return None


def _normalize_event(
    row: Mapping[str, object],
    *,
    kind: str,
    run_id: str,
    scenario: str,
    source_file: Path,
) -> ControllerEvent:
    raw_status = _first_nonempty(
        row,
        (
            "ack_status",
            "application_status",
            "status",
            "result",
            "state",
            "deployment_status",
        ),
        "unknown",
    )
    client_id = _first_nonempty(row, ("client_id", "client", "client_name", "node_id"), "unknown")
    policy_id = _first_nonempty(row, ("policy_id", "policy", "policy_name", "id"), "unknown")
    reason_code = _first_nonempty(row, ("reason_code", "reason", "error_code", "message"), "unknown")

    return ControllerEvent(
        run_id=str(row.get("run_id") or run_id),
        scenario=str(row.get("scenario") or scenario),
        kind=kind,
        timestamp=_first_nonempty(row, ("timestamp", "time", "created_at")),
        client_id=client_id,
        policy_id=policy_id,
        sequence_no=_first_nonempty(row, ("sequence_no", "sequence", "seq")),
        status=_normalize_status(raw_status, kind=kind),
        reason_code=reason_code,
        source_file=str(source_file),
    )


def _load_csv_events(path: Path, results_root: Path) -> list[ControllerEvent]:
    kind = _infer_kind_from_path(path)
    if kind is None:
        return []

    run_id, scenario = _infer_run_and_scenario(path, results_root)
    events: list[ControllerEvent] = []

    with path.open("r", newline="", encoding="utf-8") as fp:
        reader = csv.DictReader(fp)
        for row in reader:
            if not any((value or "").strip() for value in row.values()):
                continue
            events.append(
                _normalize_event(
                    row,
                    kind=kind,
                    run_id=run_id,
                    scenario=scenario,
                    source_file=path,
                )
            )
    return events


def _infer_kind_from_json(row: Mapping[str, object], path: Path) -> str | None:
    value = _first_nonempty(row, ("event_type", "kind", "type"), "")
    value_l = value.lower()
    if "ack" in value_l:
        return "ack"
    if "status" in value_l or "applied" in value_l or "deployment" in value_l:
        return "status"
    return _infer_kind_from_path(path)


def _load_jsonl_events(path: Path, results_root: Path) -> list[ControllerEvent]:
    run_id, scenario = _infer_run_and_scenario(path, results_root)
    events: list[ControllerEvent] = []

    with path.open("r", encoding="utf-8") as fp:
        for line_no, line in enumerate(fp, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"invalid JSONL at {path}:{line_no}: {exc}") from exc
            if not isinstance(row, dict):
                continue
            kind = _infer_kind_from_json(row, path)
            if kind not in {"ack", "status"}:
                continue
            events.append(
                _normalize_event(
                    row,
                    kind=kind,
                    run_id=run_id,
                    scenario=scenario,
                    source_file=path,
                )
            )
    return events


def _candidate_files(results_root: Path) -> Iterable[Path]:
    for path in sorted(results_root.rglob("*")):
        if not path.is_file():
            continue
        suffix = path.suffix.lower()
        name = path.name.lower()
        if suffix == ".csv" and ("ack" in name or "status" in name):
            yield path
        elif suffix == ".jsonl" and any(hint in path.stem.lower() for hint in JSONL_FILE_HINTS):
            yield path


def load_controller_events(results_root: str | Path, run_ids: Sequence[str] | None = None) -> list[ControllerEvent]:
    """Load and normalize controller-side ACK/status feedback events.

    Parameters
    ----------
    results_root:
        Root directory containing ``results/<run_id>/<scenario>/...`` style outputs.
    run_ids:
        Optional run-id filter.  When omitted, all discovered runs are loaded.
    """

    root = Path(results_root)
    selected = set(run_ids or [])
    events: list[ControllerEvent] = []

    if not root.exists():
        return []

    for path in _candidate_files(root):
        run_id, _scenario = _infer_run_and_scenario(path, root)
        if selected and run_id not in selected:
            continue
        if path.suffix.lower() == ".csv":
            events.extend(_load_csv_events(path, root))
        elif path.suffix.lower() == ".jsonl":
            events.extend(_load_jsonl_events(path, root))

    return events


def _rate(numerator: int, denominator: int) -> str:
    if denominator <= 0:
        return "0.000000"
    return f"{numerator / denominator:.6f}"


def _group_by(events: Iterable[ControllerEvent], keys: Sequence[str]) -> dict[tuple[str, ...], list[ControllerEvent]]:
    groups: dict[tuple[str, ...], list[ControllerEvent]] = defaultdict(list)
    for event in events:
        key = tuple(str(getattr(event, k)) for k in keys)
        groups[key].append(event)
    return groups


def aggregate_deployment(events: Sequence[ControllerEvent]) -> list[dict[str, str]]:
    """Aggregate accepted/rejected/applied/failed rates by run and scenario."""

    rows: list[dict[str, str]] = []
    for (run_id, scenario), group in sorted(_group_by(events, ("run_id", "scenario")).items()):
        ack_counts = Counter(e.status for e in group if e.kind == "ack")
        status_counts = Counter(e.status for e in group if e.kind == "status")
        ack_total = sum(ack_counts.values())
        status_total = sum(status_counts.values())

        rows.append(
            {
                "schema_version": str(SCHEMA_VERSION),
                "run_id": run_id,
                "scenario": scenario,
                "ack_total": str(ack_total),
                "ack_accepted": str(ack_counts.get("accepted", 0)),
                "ack_rejected": str(ack_counts.get("rejected", 0)),
                "ack_expired": str(ack_counts.get("expired", 0)),
                "ack_invalid_signature": str(ack_counts.get("invalid_signature", 0)),
                "ack_timeout": str(ack_counts.get("timeout", 0)),
                "ack_accepted_rate": _rate(ack_counts.get("accepted", 0), ack_total),
                "ack_rejected_rate": _rate(ack_counts.get("rejected", 0), ack_total),
                "ack_timeout_rate": _rate(ack_counts.get("timeout", 0), ack_total),
                "status_total": str(status_total),
                "status_applied": str(status_counts.get("applied", 0)),
                "status_failed": str(status_counts.get("failed", 0)),
                "status_timeout": str(status_counts.get("timeout", 0)),
                "status_applied_rate": _rate(status_counts.get("applied", 0), status_total),
                "status_failed_rate": _rate(status_counts.get("failed", 0), status_total),
                "status_timeout_rate": _rate(status_counts.get("timeout", 0), status_total),
            }
        )
    return rows


def aggregate_clients(events: Sequence[ControllerEvent]) -> list[dict[str, str]]:
    """Aggregate feedback rates by run, scenario, and client."""

    rows: list[dict[str, str]] = []
    for (run_id, scenario, client_id), group in sorted(
        _group_by(events, ("run_id", "scenario", "client_id")).items()
    ):
        ack_counts = Counter(e.status for e in group if e.kind == "ack")
        status_counts = Counter(e.status for e in group if e.kind == "status")
        ack_total = sum(ack_counts.values())
        status_total = sum(status_counts.values())
        rows.append(
            {
                "schema_version": str(SCHEMA_VERSION),
                "run_id": run_id,
                "scenario": scenario,
                "client_id": client_id,
                "ack_total": str(ack_total),
                "ack_accepted": str(ack_counts.get("accepted", 0)),
                "ack_rejected": str(ack_counts.get("rejected", 0)),
                "ack_timeout": str(ack_counts.get("timeout", 0)),
                "ack_accepted_rate": _rate(ack_counts.get("accepted", 0), ack_total),
                "status_total": str(status_total),
                "status_applied": str(status_counts.get("applied", 0)),
                "status_failed": str(status_counts.get("failed", 0)),
                "status_timeout": str(status_counts.get("timeout", 0)),
                "status_applied_rate": _rate(status_counts.get("applied", 0), status_total),
            }
        )
    return rows


def aggregate_reason_codes(events: Sequence[ControllerEvent]) -> list[dict[str, str]]:
    """Aggregate reason-code counts by run, scenario, event kind, and status."""

    counter: Counter[tuple[str, str, str, str, str]] = Counter()
    for event in events:
        counter[(event.run_id, event.scenario, event.kind, event.status, event.reason_code)] += 1

    return [
        {
            "schema_version": str(SCHEMA_VERSION),
            "run_id": run_id,
            "scenario": scenario,
            "kind": kind,
            "status": status,
            "reason_code": reason_code,
            "count": str(count),
        }
        for (run_id, scenario, kind, status, reason_code), count in sorted(counter.items())
    ]


def comparison_summary(events: Sequence[ControllerEvent]) -> list[dict[str, str]]:
    """Return a compact paper-ready comparison table."""

    rows = []
    for row in aggregate_deployment(events):
        rows.append(
            {
                "run_id": row["run_id"],
                "scenario": row["scenario"],
                "ack_total": row["ack_total"],
                "ack_accepted_rate": row["ack_accepted_rate"],
                "ack_rejected_rate": row["ack_rejected_rate"],
                "ack_timeout_rate": row["ack_timeout_rate"],
                "status_total": row["status_total"],
                "status_applied_rate": row["status_applied_rate"],
                "status_failed_rate": row["status_failed_rate"],
                "status_timeout_rate": row["status_timeout_rate"],
            }
        )
    return rows


def _write_csv(path: Path, rows: Sequence[Mapping[str, str]], fieldnames: Sequence[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.DictWriter(fp, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_analysis_outputs(events: Sequence[ControllerEvent], output_dir: str | Path) -> dict[str, Path]:
    """Write normalized events and aggregate CSV/JSON files."""

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    normalized_rows = [event.as_row() for event in events]
    deployment_rows = aggregate_deployment(events)
    client_rows = aggregate_clients(events)
    reason_rows = aggregate_reason_codes(events)
    comparison_rows = comparison_summary(events)

    paths = {
        "normalized_csv": out / "controller_events_normalized.csv",
        "deployment_csv": out / "controller_deployment_summary.csv",
        "deployment_json": out / "controller_deployment_summary.json",
        "client_csv": out / "controller_client_summary.csv",
        "reason_code_csv": out / "controller_reason_code_summary.csv",
        "comparison_csv": out / "controller_comparison_summary.csv",
    }

    _write_csv(
        paths["normalized_csv"],
        normalized_rows,
        (
            "schema_version",
            "run_id",
            "scenario",
            "kind",
            "timestamp",
            "client_id",
            "policy_id",
            "sequence_no",
            "status",
            "reason_code",
            "source_file",
        ),
    )
    _write_csv(
        paths["deployment_csv"],
        deployment_rows,
        (
            "schema_version",
            "run_id",
            "scenario",
            "ack_total",
            "ack_accepted",
            "ack_rejected",
            "ack_expired",
            "ack_invalid_signature",
            "ack_timeout",
            "ack_accepted_rate",
            "ack_rejected_rate",
            "ack_timeout_rate",
            "status_total",
            "status_applied",
            "status_failed",
            "status_timeout",
            "status_applied_rate",
            "status_failed_rate",
            "status_timeout_rate",
        ),
    )
    _write_csv(
        paths["client_csv"],
        client_rows,
        (
            "schema_version",
            "run_id",
            "scenario",
            "client_id",
            "ack_total",
            "ack_accepted",
            "ack_rejected",
            "ack_timeout",
            "ack_accepted_rate",
            "status_total",
            "status_applied",
            "status_failed",
            "status_timeout",
            "status_applied_rate",
        ),
    )
    _write_csv(
        paths["reason_code_csv"],
        reason_rows,
        (
            "schema_version",
            "run_id",
            "scenario",
            "kind",
            "status",
            "reason_code",
            "count",
        ),
    )
    _write_csv(
        paths["comparison_csv"],
        comparison_rows,
        (
            "run_id",
            "scenario",
            "ack_total",
            "ack_accepted_rate",
            "ack_rejected_rate",
            "ack_timeout_rate",
            "status_total",
            "status_applied_rate",
            "status_failed_rate",
            "status_timeout_rate",
        ),
    )

    with paths["deployment_json"].open("w", encoding="utf-8") as fp:
        json.dump(
            {
                "schema_version": SCHEMA_VERSION,
                "event_count": len(events),
                "deployment_summary": deployment_rows,
                "client_summary": client_rows,
                "reason_code_summary": reason_rows,
            },
            fp,
            ensure_ascii=False,
            indent=2,
        )
        fp.write("\n")

    return paths


def _parse_run_ids(value: str | None) -> list[str] | None:
    if not value:
        return None
    run_ids = [item.strip() for item in value.split(",") if item.strip()]
    return run_ids or None


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Aggregate AOMQTT controller-side ACK/status feedback.")
    parser.add_argument("--results-dir", default="results", help="Root directory containing evaluation results.")
    parser.add_argument(
        "--output-dir",
        default="results/v092_controller_analysis",
        help="Directory where analysis files will be written.",
    )
    parser.add_argument(
        "--run-id",
        default=None,
        help="Optional comma-separated run_id filter, e.g. run-a,run-b.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    events = load_controller_events(args.results_dir, run_ids=_parse_run_ids(args.run_id))
    paths = write_analysis_outputs(events, args.output_dir)

    print(f"loaded_events={len(events)}")
    for name, path in paths.items():
        print(f"{name}={path}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
