services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: aomqtt-mosquitto
    ports:
      - "127.0.0.1:1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.docker.conf:/mosquitto/config/mosquitto.conf:ro
